# Generated by Django 4.2.7 on 2024-03-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_alter_jobseeker_address_alter_jobseeker_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
    ]
