# Generated by Django 4.2.7 on 2024-04-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_alter_application_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата приёма'),
        ),
    ]
