# Generated by Django 4.2.7 on 2024-04-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_alter_employee_date_of_employment'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Описание профиля'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos', verbose_name='Логотип организации'),
        ),
    ]
