# Generated by Django 4.2.7 on 2023-12-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0007_jobseeker_workexperience_educationofjobseeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Описание профиля'),
        ),
        migrations.AlterField(
            model_name='address',
            name='map_link',
            field=models.URLField(blank=True, max_length=2083, null=True, verbose_name='Ссылка на карты'),
        ),
        migrations.AlterField(
            model_name='educationofjobseeker',
            name='year_received',
            field=models.IntegerField(choices=[(1950, '1950'), (1951, '1951'), (1952, '1952'), (1953, '1953'), (1954, '1954'), (1955, '1955'), (1956, '1956'), (1957, '1957'), (1958, '1958'), (1959, '1959'), (1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023')], verbose_name='Год получения'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skill',
            field=models.ManyToManyField(blank=True, to='domain.skill', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='domain.specialization', verbose_name='Специализация'),
        ),
        migrations.CreateModel(
            name='SoftwareAndHardwareToolOfJobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='Уровень владения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.jobseeker', verbose_name='Соискатель')),
                ('software_and_hardware_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.softwareandhardwaretool', verbose_name='Программно-техническое средство')),
            ],
            options={
                'verbose_name': 'Уровень владения программно-техническим средством',
                'verbose_name_plural': 'Уровни владения программно-техническими средствами',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('desired_salary', models.CharField(max_length=100, verbose_name='Желаемая зарплата')),
                ('willing_to_relocate', models.CharField(choices=[('yes', 'Готов к переезду'), ('no', 'Не готов к переезду'), ('maybe', 'Может быть'), ('not_specified', 'Не указано')], default='not_specified', max_length=13, verbose_name='Готовность к переезду')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия резюме')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.jobseeker', verbose_name='Соискатель')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.workschedule', verbose_name='График работы')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('time_of_publication', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('time_of_moderation', models.DateTimeField(blank=True, null=True, verbose_name='Время модерации')),
                ('time_of_edition', models.DateTimeField(blank=True, null=True, verbose_name='Время изменения')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.jobseeker', verbose_name='Соискатель')),
                ('software_and_hardware_tool', models.ManyToManyField(blank=True, to='domain.softwareandhardwaretool', verbose_name='Программно-техническое средство')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='AttachmentToPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachment_to_publications', verbose_name='Приложение к публикации')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.publication')),
            ],
            options={
                'verbose_name': 'Приложение к публикации',
                'verbose_name_plural': 'Приложения к публикациям',
            },
        ),
    ]
