# Generated by Django 4.2.7 on 2024-04-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0007_organization_about_organization_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Описание организации'),
        ),
    ]
