# Generated by Django 4.2.7 on 2024-04-14 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_alter_jobseeker_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('pending_approval', 'На согласовании'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='JobInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_interview', models.DateTimeField(verbose_name='Время собеседования')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Отзыв сотрудника')),
                ('application_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.applicationsresponses', verbose_name='Отклик на заявку')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Собеседование',
                'verbose_name_plural': 'Собеседования',
            },
        ),
    ]
