# Generated by Django 4.2.7 on 2023-12-07 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_jobseeker_about_alter_address_map_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='okved_kode',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Код ОКВЭД'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_application', models.DateField(auto_now_add=True, verbose_name='Дата заявки')),
                ('desired_date', models.DateField(blank=True, null=True, verbose_name='Желательный срок')),
                ('final_date', models.DateField(blank=True, null=True, verbose_name='Крайний срок')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('salary', models.CharField(max_length=255, verbose_name='Зарплата')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт (лет)')),
                ('date_of_completion', models.DateField(verbose_name='Дата выполнения')),
                ('date_of_cancellation', models.DateField(verbose_name='Дата отмены')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('pending_approval', 'На согласовании'), ('completed', 'Завершена'), ('canceled', 'Отменена'), ('payment_received', 'Получена оплата')], default='new', max_length=20, verbose_name='Статус')),
                ('education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='domain.educationlevel', verbose_name='Уровень образования')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.employee', verbose_name='Работник')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.employer', verbose_name='Работодатель')),
                ('skills', models.ManyToManyField(blank=True, to='domain.skill', verbose_name='Навыки')),
                ('software_and_hardware_tools', models.ManyToManyField(blank=True, to='domain.softwareandhardwaretool', verbose_name='Требуемые программно-технические средства')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.specialization', verbose_name='Специализация')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.workschedule', verbose_name='График работы')),
            ],
            options={
                'verbose_name': 'Заявка на подбор специалиста',
                'verbose_name_plural': 'Заявки на подбор специалистов',
            },
        ),
    ]
