# Generated by Django 4.2.7 on 2024-04-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0009_alter_application_status_jobinterview'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinterview',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('accepted', 'Принят'), ('rejected', 'Отклонен'), ('passed', 'Прошло'), ('with_feedback', 'С отзывом')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
