# Generated by Django 4.2.7 on 2023-12-17 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0009_organization_okved_kode_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='position',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Должность'),
        ),
    ]
