# Generated by Django 4.2.7 on 2023-12-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0010_alter_employer_organization_alter_employer_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=18, verbose_name='Номер телефона'),
        ),
    ]
