# Generated by Django 4.2.7 on 2024-04-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0010_jobinterview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('pending_approval', 'На согласовании'), ('completed', 'Завершена'), ('overdue', 'Просрочена'), ('canceled', 'Отменена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='applicationsresponses',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('under_review', 'Рассмотрение'), ('accepted', 'Принят'), ('overdue', 'Просрочена'), ('rejected', 'Отклонен'), ('withdrawn', 'Отозван')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='jobinterview',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('accepted', 'Принят'), ('rejected', 'Отклонен'), ('overdue', 'Просрочена'), ('passed', 'Прошло'), ('with_feedback', 'С отзывом')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
