# Generated by Django 4.2.7 on 2023-12-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0011_alter_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_of_cancellation',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_of_completion',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
