# Generated by Django 4.2.7 on 2023-12-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0012_alter_application_date_of_cancellation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_of_application',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки'),
        ),
    ]
