# Generated by Django 4.2.7 on 2024-04-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0012_alter_applicationsresponses_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='work_location_preference',
            field=models.CharField(choices=[('remote', 'Удалённая работа'), ('local', 'Работа в городе проживания'), ('relocation', 'Готовность к переезду')], default='local', max_length=15, verbose_name='Место желаемой работы'),
        ),
    ]
