# Generated by Django 4.2.7 on 2024-04-26 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0013_jobseeker_work_location_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinterview',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.address', verbose_name='Место собеседования'),
        ),
        migrations.AddField(
            model_name='jobinterview',
            name='link',
            field=models.URLField(blank=True, max_length=2083, null=True, verbose_name='Ссылка на онлайн собеседование'),
        ),
    ]
