# Generated by Django 4.2.7 on 2024-04-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0014_jobinterview_address_jobinterview_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_of_last_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней правки'),
        ),
    ]
