# Generated by Django 4.2.7 on 2024-05-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0015_application_date_of_last_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Описание организации'),
        ),
    ]
