# Generated by Django 4.2.7 on 2024-01-10 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0015_alter_educationofjobseeker_year_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationsResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_response', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика на заявку')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('under_review', 'Рассмотрение'), ('accepted', 'Принят'), ('rejected', 'Отклонен'), ('withdrawn', 'Отозван')], default='pending', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.application', verbose_name='Заявка на подбор')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.jobseeker', verbose_name='Соискатель')),
            ],
        ),
    ]
