# Generated by Django 4.2.7 on 2024-05-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0016_alter_organization_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
    ]
