# Generated by Django 4.2.7 on 2024-01-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0016_applicationsresponses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationsresponses',
            options={'verbose_name': 'Отклик на заявку', 'verbose_name_plural': 'Отклики на заявки'},
        ),
        migrations.AddField(
            model_name='applicationsresponses',
            name='evaluation',
            field=models.FloatField(default=0, verbose_name='Предварительная оценка соответствия соискателя'),
            preserve_default=False,
        ),
    ]
