# Generated by Django 4.2.7 on 2024-01-11 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0017_alter_applicationsresponses_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationlevel',
            name='code',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Код уровня профессионального образования'),
            preserve_default=False,
        ),
    ]
