# Generated by Django 4.2.7 on 2024-05-05 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0017_alter_jobseeker_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.BooleanField(blank=True, null=True, verbose_name='Факт подтверждения')),
                ('file', models.ImageField(upload_to='attachment_to_confirmation', verbose_name='Фотография документа')),
            ],
            options={
                'verbose_name': 'Приложение к публикации',
                'verbose_name_plural': 'Приложения к публикациям',
            },
        ),
        migrations.AddField(
            model_name='educationofjobseeker',
            name='document_confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.documentconfirmation', verbose_name='Подтверждение образования'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='document_confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.documentconfirmation', verbose_name='Подтверждение образования'),
        ),
    ]
