# Generated by Django 4.2.7 on 2024-05-05 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0018_documentconfirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationofjobseeker',
            name='document_confirmation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.documentconfirmation', verbose_name='Подтверждение образования'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='document_confirmation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.documentconfirmation', verbose_name='Подтверждение образования'),
        ),
    ]
