# Generated by Django 4.2.7 on 2024-05-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0022_workformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='work_format',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='domain.workformat', verbose_name='Формат работы'),
        ),
    ]
