# Generated by Django 4.2.7 on 2024-05-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0023_application_work_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationofjobseeker',
            name='document_confirmation',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='document_confirmation',
        ),
    ]
