# Generated by Django 4.2.7 on 2024-05-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0024_remove_educationofjobseeker_document_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwareandhardwaretool',
            options={'verbose_name': 'Ключевой навык', 'verbose_name_plural': 'Ключевые навыки'},
        ),
    ]
